// Processes the raw UCI Cleveland Heart Disease dataset into a typed TS module.
// - Cleans '?' missing values (drops affected rows, matching standard practice).
// - Fits a standardized logistic-regression risk model via gradient descent.
// - Emits src/data/patients.ts with the cleaned rows + model coefficients.
//
// Source: Detrano et al., UCI Machine Learning Repository (Cleveland clinic).
// Run: node scripts/process-data.mjs /tmp/cleveland.data
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const RAW = process.argv[2] || '/tmp/cleveland.data';
const text = readFileSync(RAW, 'utf8').trim();

// Column order in processed.cleveland.data
const COLS = ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','num'];

const rows = [];
for (const line of text.split('\n')) {
  const parts = line.trim().split(',');
  if (parts.length !== 14) continue;
  if (parts.some((p) => p === '?')) continue; // drop rows with missing ca/thal (6 rows)
  const r = {};
  COLS.forEach((c, i) => { r[c] = Number(parts[i]); });
  // Binary target: 0 = no disease, 1-4 = presence of disease -> 1
  r.disease = r.num > 0 ? 1 : 0;
  delete r.num;
  rows.push(r);
}

// Features used by the risk model (clinically interpretable subset).
const FEATURES = ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal'];

// Standardize
const mean = {}, std = {};
for (const f of FEATURES) {
  const vals = rows.map((r) => r[f]);
  const m = vals.reduce((a, b) => a + b, 0) / vals.length;
  const v = vals.reduce((a, b) => a + (b - m) ** 2, 0) / vals.length;
  mean[f] = m;
  std[f] = Math.sqrt(v) || 1;
}

const X = rows.map((r) => FEATURES.map((f) => (r[f] - mean[f]) / std[f]));
const y = rows.map((r) => r.disease);

// Logistic regression via batch gradient descent
const n = X.length, d = FEATURES.length;
let w = new Array(d).fill(0), b = 0;
const lr = 0.1, epochs = 4000, lambda = 0.01;
const sigmoid = (z) => 1 / (1 + Math.exp(-z));
for (let e = 0; e < epochs; e++) {
  const gw = new Array(d).fill(0); let gb = 0;
  for (let i = 0; i < n; i++) {
    let z = b;
    for (let j = 0; j < d; j++) z += w[j] * X[i][j];
    const p = sigmoid(z);
    const err = p - y[i];
    for (let j = 0; j < d; j++) gw[j] += err * X[i][j];
    gb += err;
  }
  for (let j = 0; j < d; j++) w[j] = w[j] - lr * (gw[j] / n + lambda * w[j]);
  b = b - lr * (gb / n);
}

// Training accuracy + AUC for an honest headline metric
let correct = 0;
const scored = [];
for (let i = 0; i < n; i++) {
  let z = b;
  for (let j = 0; j < d; j++) z += w[j] * X[i][j];
  const p = sigmoid(z);
  scored.push({ p, y: y[i] });
  if ((p >= 0.5 ? 1 : 0) === y[i]) correct++;
}
const acc = correct / n;
// AUC via rank statistic
const pos = scored.filter((s) => s.y === 1).map((s) => s.p);
const neg = scored.filter((s) => s.y === 0).map((s) => s.p);
let wins = 0;
for (const pp of pos) for (const nn of neg) wins += pp > nn ? 1 : pp === nn ? 0.5 : 0;
const auc = wins / (pos.length * neg.length);

const coef = {};
FEATURES.forEach((f, j) => { coef[f] = w[j]; });

const out = `// AUTO-GENERATED by scripts/process-data.mjs — do not edit by hand.
// Real data: UCI Heart Disease (Cleveland), Detrano et al. ${rows.length} patients after
// dropping ${'6'} rows with missing values. Risk model = standardized logistic regression
// fit in-repo (train accuracy ${(acc * 100).toFixed(1)}%, ROC-AUC ${auc.toFixed(3)}).

export interface Patient {
  age: number; sex: number; cp: number; trestbps: number; chol: number;
  fbs: number; restecg: number; thalach: number; exang: number; oldpeak: number;
  slope: number; ca: number; thal: number; disease: number;
}

export const FEATURES = ${JSON.stringify(FEATURES)} as const;
export type Feature = (typeof FEATURES)[number];

export const FEATURE_MEAN: Record<Feature, number> = ${JSON.stringify(mean, null, 2)};
export const FEATURE_STD: Record<Feature, number> = ${JSON.stringify(std, null, 2)};

// Logistic-regression coefficients on STANDARDIZED features.
export const MODEL_COEF: Record<Feature, number> = ${JSON.stringify(coef, null, 2)};
export const MODEL_INTERCEPT = ${b};

export const MODEL_METRICS = { accuracy: ${acc}, auc: ${auc}, n: ${rows.length} };

export const patients: Patient[] = ${JSON.stringify(rows)};
`;

mkdirSync(new URL('../src/data/', import.meta.url), { recursive: true });
writeFileSync(new URL('../src/data/patients.ts', import.meta.url), out);
console.log(`Wrote ${rows.length} patients. acc=${(acc*100).toFixed(1)}% auc=${auc.toFixed(3)}`);
console.log('Top risk drivers (|standardized coef|):');
console.log([...FEATURES].sort((a,b)=>Math.abs(coef[b])-Math.abs(coef[a])).slice(0,6).map(f=>`${f}: ${coef[f].toFixed(2)}`).join('  '));
